export type ConnectionState = 'idle' | 'connecting' | 'synchronizing' | 'connected' | 'reconnecting' | 'disconnected' | 'error'

export type {
  ActionDescriptor,
  BuildTowerAction,
  CellKind,
  EntityDelta,
  EnemyState,
  EnemyThreat,
  GameNoticeUpdate,
  GameUiState,
  GameUiStateUpdate,
  GameStatePatch,
  GameOutcome,
  GameAction,
  GameCell,
  GameState,
  PveBoardPieceState,
  PveEnemyState,
  PveGameAction,
  PveLaneWaveState,
  PveMatchState,
  PvePlayerState,
  PveTrayPieceState,
  PveTraySlotState,
  GridPosition,
  ResourceState,
  SellTowerAction,
  SpawnGroup,
  TickEnvelope,
  TowerBlueprint,
  TowerFootprint,
  TowerState,
  TowerStatus,
  UpgradeTowerAction,
  WaveConfig,
  SoldierType,
} from '../../shared/contracts/game'
