export type ConnectionState = 'idle' | 'connecting' | 'connected' | 'reconnecting' | 'disconnected' | 'error'

export type {
  ActionDescriptor,
  BuildTowerAction,
  CellKind,
  EntityDelta,
  EnemyState,
  EnemyThreat,
  GameNoticeUpdate,
  GameUiState,
  GameUiStateUpdate,
  GameStatePatch,
  GameOutcome,
  GameAction,
  GameCell,
  GameState,
  GridPosition,
  ResourceState,
  SellTowerAction,
  SpawnGroup,
  TickEnvelope,
  TowerBlueprint,
  TowerFootprint,
  TowerState,
  TowerStatus,
  UpgradeTowerAction,
  WaveConfig,
} from '../../shared/contracts/game'